const HttpErrorType = {
    DATABASE_ERROR: 'DATABASE_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    API_ERROR: 'API_ERROR',
    BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
    UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    UNPROCESSABLE_ENTITY_ERROR: 'UNPROCESSABLE_ENTITY_ERROR',
    CONFLICT_ERROR: 'CONFLICT_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
}

export  { HttpErrorType }